// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import com.ctre.phoenix.motorcontrol.NeutralMode;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.math.filter.SlewRateLimiter;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants.IntakeConstants;
import frc.robot.Robot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/** */
public class Intake extends SubsystemBase {

  // private static Spark intakeMotor = new Spark(IntakeConstants.INTAKER_ADDRESS);
  private static WPI_TalonSRX intakeTalon = new WPI_TalonSRX(IntakeConstants.MoveBot);
  private static DoubleSolenoid firstSolenoid = Robot.firstSolenoid;
  private static DoubleSolenoid secondSolenoid = Robot.secondSolenoid;
  public SlewRateLimiter filter = new SlewRateLimiter(0.5);
  // public static DigitalInput intakeSwitch = new DigitalInput(
  //  IntakeConstants.INTAKER_SWITCH
  // );

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  public Intake() {

    {
      intakeTalon.set(0);
    }
    intakeTalon.setNeutralMode(NeutralMode.Brake);
  }

  public void initDefaultCommand() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // Set the default command for a subsystem here.
    // setDefaultCommand(new MySpecialCommand());
  }

  public void periodic() {
    // SmartDashboard.putBoolean("IntakeSwitch.get", intakeSwitch.get());
    // Put code here to be run every loop

  }

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

  // Put methods for controlling this subsystem
  // here. Call these from Commands.
  public static void testMotors(double motorSpeed) {
    // spark.set(motorSpeed);
  }

  // public void intakePowerCell() {
  /*if (!intakeSwitch.get()){
      //intakeMotor.set(IntakeConstants.INTAKER_MOTOR_SPEED);
  }
  else{
      //intakeMotor.set(0);
  }*/
  // intakeMotor.set(motorSpeed);
  // }

  public void intakePowerCell() {
    // if (!intakeSwitch.get()){
    intakeTalon.set(0.5);
    // }
    // else{
    //    intakeMotor.set(0);
  }

  public void intakeStop() {
    intakeTalon.set(0);
  }

  public void extendSolenoid() {
    firstSolenoid.set(DoubleSolenoid.Value.kReverse);
    secondSolenoid.set(DoubleSolenoid.Value.kForward);
  }

  public void retractSolenoid() {
    firstSolenoid.set(DoubleSolenoid.Value.kForward);
    secondSolenoid.set(DoubleSolenoid.Value.kReverse);
  }

  {
    // if (intakeSwitch.get() == false);
    // intakeVictor.set(0);
  }

  // public static boolean getButtonState() {
  //  return (!intakeSwitch.get());
  //    return true;
  // }

  public static void stop() {
    intakeTalon.set(0);
  }

  public static void flush() {}

  // public boolean finished() {
  //  return getButtonState();
  // }
}
